### ISSUE TITLE
Installation Issues on Arch Linux

### ISSUE THREAD

**Issue by xFadedxShadow** [JohnHeikens/IntelliSkript#93]
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module './skript/section/SkriptFile'
Require stack:
- /home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js'
  ]
}

Node.js v20.9.0
[Info  - 8:32:31 AM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module './skript/section/SkriptFile'
Require stack:
- /home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js'
  ]
}

Node.js v20.9.0
[Info  - 8:32:31 AM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module './skript/section/SkriptFile'
Require stack:
- /home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js'
  ]
}

Node.js v20.9.0
[Info  - 8:32:31 AM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module './skript/section/SkriptFile'
Require stack:
- /home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js'
  ]
}

Node.js v20.9.0
[Info  - 8:32:31 AM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1058
  throw err;
  ^

Error: Cannot find module './skript/section/SkriptFile'
Require stack:
- /home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1055:15)
    at Module._load (node:internal/modules/cjs/loader:908:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/xfadedxshadow/.vscode-oss/extensions/johnheikens.intelliskript-1.7.3/server/out/server.js'
  ]
}

Node.js v20.9.0
[Error - 8:32:31 AM] Connection to server got closed. Server will not be restarted.

**After installation of the extension on linux using codium**

**Comment by JohnHeikens** [comment]
![image](https://github.com/JohnHeikens/IntelliSkript/assets/50964021/ebc8ecb5-3084-48a7-a589-302ea4469f99)
aha! the compiled js folders don't update casing automatically on windows, since windows doesn't distinguish between upper or lower cased folders.

**Comment by JohnHeikens** [comment]
patched and published! let me know if you have more trouble!
